apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-boot-react-app.mongodb.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "spring-boot-react-app.mongodb.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "spring-boot-react-app.mongodb.fullname" . }}
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image }}:{{ .Values.mongodb.tag }}"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.username }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodb.password }}
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          emptyDir: {}
