apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-react-app.mongodb.fullname" . }}
spec:
  type: {{ .Values.mongodbService.type }}
  ports:
    - port: {{ .Values.mongodbService.port }}
      targetPort: 27017
  selector:
    app: {{ include "spring-boot-react-app.mongodb.fullname" . }}
