apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-react-app.fullname" . }}
  labels:
    {{- include "spring-boot-react-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.reactApp.service.type }}
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spring-boot-react-app.selectorLabels" . | nindent 4 }}
