apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-spring-boot-service
spec:
  type: {{ .Values.springBootApp.service.type }}
  ports:
    - port: 8088
      targetPort: 8088
  selector:
    app: {{ .Release.Name }}-spring-boot
