replicaCount: 1
mongodb:
  image: mongo
  tag: latest
  username: read
  password: singh
  database: LindaDb
imagePullSecrets: 
  - name: ecr-login-secret
env:
  REACT_APP_PROD_IP: "35.244.2.180"
  REACT_APP_PROD_PORT: "8088"
  API_BASE_URL: "http://35.244.2.180:30002"
