apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "springbootapp.fullname" . }}-config
data:
  application.properties: |
    spring.data.mongodb.uri=mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@{{ include "springbootapp.mongodb.fullname" . }}:{{ .Values.mongodbService.port }}/{{ .Values.mongodb.database }}
